### ISSUE TITLE
Linux server directory problem 

### ISSUE THREAD

**Issue by AXCWG** [Bumer-32/I-Want-To-Control-My-Server#10]
root@iZ2ze3qm14oebwj7c6a0d9Z:/mnt/fhd# ls
     ForUpload  'ForUpload\config\iwtcms'  'ForUpload\config\iwtcms\iwtcms.json'   SwapFile   TestOnlyServer   grandServer   lost+found   wget-log
    root@iZ2ze3qm14oebwj7c6a0d9Z:/mnt/fhd# 

The server was under /mnt/fhd/ForUpload, like where the start script and the 'mods' directory takes place, however the mod is generating its configs outside the game folder, in the root folder of the drive's mounting point.

**Comment by Bumer-32** [comment]
@AXCWG Fixed in 1.2.0-Fix_2
